---
collections:
  - name: community.general
  - name: ansible.posix
  - name: middleware_automation.infinispan
    version: "==1.0.0"
  - name: middleware_automation.keycloak
    version: "==1.0.0"
  - name: middleware_automation.wildfly
    version: "==1.0.0"
  - name: middleware_automation.jws
    version: "==1.0.0"
  - name: middleware_automation.redhat_csp_download
  - name: middleware_automation.jcliff
