---
collections:
  - name: community.general
  - name: ansible.posix
  - name: ansible.netcommon
  - name: middleware_automation.infinispan
    version: "==1.1.3"
  - name: middleware_automation.keycloak
    version: "==1.2.4"
  - name: middleware_automation.wildfly
    version: "==1.3.2"
  - name: middleware_automation.amq
    version: "==1.3.4"
  - name: middleware_automation.jws
    version: "==1.2.3"
  - name: middleware_automation.common
    version: "==1.1.0"
  - name: middleware_automation.redhat_csp_download
    version: "==1.2.2"
  - name: middleware_automation.jcliff
    version: "==0.0.23"
