---
collections:
  - name: ansible.posix
  - name: ansible.netcommon
  - name: middleware_automation.infinispan
    version: "==1.2.0"
  - name: middleware_automation.keycloak
    version: "==1.2.8"
  - name: middleware_automation.wildfly
    version: "==1.3.4"
  - name: middleware_automation.amq
    version: "==1.3.8"
  - name: middleware_automation.amq_streams
    version: "==0.0.5"
  - name: middleware_automation.jws
    version: "==1.2.3"
  - name: middleware_automation.common
    version: "==1.1.2"
  - name: middleware_automation.jbcs
    version: "==1.0.3"
