---
collections:
  - name: community.general
  - name: ansible.posix
  - name: ansible.netcommon
  - name: middleware_automation.infinispan
    version: "==1.0.1"
  - name: middleware_automation.keycloak
    version: "==1.0.2"
  - name: middleware_automation.wildfly
    version: "==1.0.1"
  - name: middleware_automation.jws
  - name: middleware_automation.redhat_csp_download
  - name: middleware_automation.jcliff
