---
name: CI

on:
  pull_request:
    branches: 
      - main
  push:
    branches:
      - main
  repository_dispatch:

env:
  COLORTERM: 'yes'
  TERM: 'xterm-256color'
  PYTEST_ADDOPTS: '--color=yes'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: 'pip'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install podman
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ansible-core ansible-navigator[ansible-core]

      - name: Build EE with Podman
        run: |
          ansible-builder build -v3 -c . -t ansible-middleware-ee:test --container-runtime=podman

      - name: Run ansible-navigator with local image
        run: |
          ansible-navigator run test.yml -i inventory --pull-policy never --eei ansible-middleware-ee:test -m stdout
        working-directory: test
